### ISSUE TITLE
missing attributes for students

### ISSUE THREAD

**Issue by danielgadea** [Laymi/shifttool#21]
need at least to include gender information for each student as well as the functionality to define gender % for shifts

car availability would be a nice add-on but only important for EM & CFF

**Comment by Peschonaut** [comment]
Gender implemented; We need size of accommodation for Euromasters...

**Comment by danielgadea** [comment]
also the functionality for shift assignment?

**Comment by Peschonaut** [comment]
Done. We do not need more data at this moment. We have to think about more data for Euromasters.
